import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {QueryClientProvider , QueryClient} from '@tanstack/react-query'
import ReactQueryProvider from "@/components/provider/ReactQueryProvider";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const queryclient = new QueryClient()
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
<ReactQueryProvider>
{children}
<ReactQueryDevtools></ReactQueryDevtools>
</ReactQueryProvider>
      </body>
    </html>
  );
}
